"""create article company map table

Revision ID: 1acb6b7c8392
Revises: 4b18cf1eb13c
Create Date: 2026-05-20 06:43:14.340175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1acb6b7c8392'
down_revision: Union[str, None] = '4b18cf1eb13c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_company_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('company_symbol', sa.String(length=50), nullable=False),
    sa.Column('match_type', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_company_map_article_id'), 'article_company_map', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_company_map_company_symbol'), 'article_company_map', ['company_symbol'], unique=False)
    op.create_index(op.f('ix_article_company_map_id'), 'article_company_map', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_company_map_id'), table_name='article_company_map')
    op.drop_index(op.f('ix_article_company_map_company_symbol'), table_name='article_company_map')
    op.drop_index(op.f('ix_article_company_map_article_id'), table_name='article_company_map')
    op.drop_table('article_company_map')
    # ### end Alembic commands ###
