"""add adm report,financial report and corporate actions

Revision ID: 2dc5e1f1ab21
Revises: 95b3764a83c9
Create Date: 2026-05-22 06:31:25.423407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dc5e1f1ab21'
down_revision: Union[str, None] = '95b3764a83c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
