"""changed the schema of scraped_article from str to Optional[str]

Revision ID: 39c55e09c224
Revises: 2dc5e1f1ab21
Create Date: 2026-05-22 06:53:49.624975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39c55e09c224'
down_revision: Union[str, None] = '2dc5e1f1ab21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
