"""add nepali company names and aliases

Revision ID: 95b3764a83c9
Revises: 9a7701bc0318
Create Date: 2026-05-20 11:19:12.001847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b3764a83c9'
down_revision: Union[str, None] = '9a7701bc0318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_symbol', sa.String(length=50), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=True),
    sa.Column('alias_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_symbol'], ['companies.symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_aliases_alias'), 'company_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_company_aliases_company_symbol'), 'company_aliases', ['company_symbol'], unique=False)
    op.create_index(op.f('ix_company_aliases_id'), 'company_aliases', ['id'], unique=False)
    op.add_column('companies', sa.Column('nepali_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'nepali_name')
    op.drop_index(op.f('ix_company_aliases_id'), table_name='company_aliases')
    op.drop_index(op.f('ix_company_aliases_company_symbol'), table_name='company_aliases')
    op.drop_index(op.f('ix_company_aliases_alias'), table_name='company_aliases')
    op.drop_table('company_aliases')
    # ### end Alembic commands ###
